/**:
  ros__parameters:
    linear_velocity_factor:
      fast: 1.0
      regular: 0.5
      slow: 0.2

    angular_velocity_factor:
      fast: 1.0
      regular: 0.5
      slow: 0.2

    # This button mapping should be adjusted to the specific controller.
    # The following map is suited for Logitech F710 in the DirectInput mode.
    # Input declaration consists of:
    # - optional negation '!',
    # - input type: 'A' for an axis or 'B' for a button,
    # - axis/button number.
    input_index_map:
      axis:
        angular_z: "A2" # Right joystick
        linear_x: "A1" # Left joystick
        linear_y: "A0" # Left joystick
      dead_man_switch: "B4" # LB
      fast_mode: "B7" # RT
      slow_mode: "B5" # RB
